#!/usr/bin/env python3
"""Convert final_report.md to Tufte HTML with embedded SVG charts and CSS."""

import sys, re, json
from pathlib import Path

def generate_html(md_file, css_file, charts_dir, lang="auto"):
    css = css_file.read_text() if css_file.exists() else ""
    md = md_file.read_text(encoding="utf-8") if md_file.exists() else "# No report"

    # Detect language from content
    if lang == "auto":
        pt_words = sum(md.lower().count(w) for w in ["de", "da", "do", "em", "para", "com", "por", "uma", "dos", "das", "seção", "tabela", "análise", "distrito", "domicílio"])
        en_words = sum(md.lower().count(w) for w in ["the", "of", "and", "for", "with", "this", "that", "from", "section", "table", "analysis", "district", "household"])
        is_pt = pt_words > en_words
    else:
        is_pt = lang == "pt"

    # HTML template strings
    h = {
        "title": "Data-Pro-Skill — Relatório Tufte" if is_pt else "Data-Pro-Skill — Tufte Report",
        "nav_links": "Saltar para: Análise | Tabelas | Gráficos" if is_pt else "Jump to: Analysis | Tables | Charts",
        "generated_by": f"Gerado por Data-Pro-Skill v2 · Estilo Tufte" if is_pt else f"Generated by Data-Pro-Skill v2 · Tufte Style",
    }

    # Convert Markdown to HTML
    html = md
    html = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html, flags=re.MULTILINE)
    html = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
    html = re.sub(r'^---$', r'<hr>', html, flags=re.MULTILINE)
    html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)
    html = re.sub(r'`(.+?)`', r'<code>\1</code>', html)

    # Tables
    lines = html.split('\n')
    table_active = False
    new_lines = []
    for i, line in enumerate(lines):
        is_table = bool(line.strip().startswith('|') and line.strip().endswith('|'))
        if is_table:
            if not table_active:
                new_lines.append('<table>')
                table_active = True
            cells = [c.strip() for c in line.strip().strip('|').split('|')]
            header_keywords = ('N', '%')
            is_header = any(c in cells for c in header_keywords)
            tag = 'th' if is_header else 'td'
            new_lines.append(f'  <tr>{"".join(f"<{tag}>{c}</{tag}>" for c in cells)}</tr>')
        else:
            if table_active:
                new_lines.append('</table>')
                table_active = False
            new_lines.append(line)
    if table_active:
        new_lines.append('</table>')
    html = '\n'.join(new_lines)

    # Blockquotes
    html = re.sub(r'^>\s?(.+)$', r'<blockquote><p>\1</p></blockquote>', html, flags=re.MULTILINE)

    # Embed SVG charts
    charts_html = ""
    if charts_dir and charts_dir.exists():
        chart_svgs = sorted(charts_dir.glob("*.svg"))
        if chart_svgs:
            charts_html = '<h2>' + ('Gráficos' if is_pt else 'Charts') + '</h2>'
            for svg_file in chart_svgs:
                svg_content = svg_file.read_text()
                charts_html += f'<div class="chart-container">{svg_content}</div>'

    full_html = f'''<!DOCTYPE html>
<html lang="{'pt-BR' if is_pt else 'en'}">
<head>
<meta charset="utf-8">
<title>{h["title"]}</title>
<style>
{css}
body {{
  font-family: 'Palatino', 'Georgia', serif;
  max-width: 960px; margin: 0 auto; padding: 2em;
}}
h1 {{ font-weight: 400; font-size: 2.2em; margin-top: 2em; }}
h2 {{ font-weight: 400; font-size: 1.6em; margin-top: 1.5em; border-bottom: 1px solid #eee; padding-bottom: 0.3em; }}
h3 {{ font-weight: 400; font-size: 1.3em; margin-top: 1.2em; color: #444; }}
table {{ border-collapse: collapse; width: 100%; margin: 1em 0; font-size: 0.9em; }}
td, th {{ border: 1px solid #ddd; padding: 5px 7px; text-align: center; }}
th {{ background: #f5f5f5; font-weight: 600; }}
tr:nth-child(even) td {{ background: #fafafa; }}
blockquote {{ border-left: 3px solid #bbb; margin: 1em 0; padding: 0.4em 1em; color: #555; font-style: italic; }}
code {{ background: #f4f4f4; padding: 1px 3px; font-size: 0.9em; }}
hr {{ border: none; border-top: 1px solid #ddd; margin: 2em 0; }}
.chart-container {{ margin: 1em 0; text-align: center; }}
.chart-container svg {{ max-width: 100%; height: auto; }}
.footer {{ margin-top: 3em; color: #999; font-size: 0.8em; text-align: center; }}
p {{ line-height: 1.6; }}
</style>
</head>
<body>
{html}
{charts_html}
<p class="footer">{h["generated_by"]}</p>
</body>
</html>'''

    html_file = md_file.with_suffix('.html')
    html_file.write_text(full_html, encoding="utf-8")
    print(f"✓ {html_file} ({html_file.stat().st_size / 1024:.0f}KB, {'pt-BR' if is_pt else 'en'})")
    return html_file

if __name__ == "__main__":
    refs = Path(sys.argv[1] if len(sys.argv) > 1 else '.dps/references')
    md_file = Path(sys.argv[2] if len(sys.argv) > 2 else '.dps/outputs/export/final_report.md')
    charts_dir = md_file.parent / "charts"
    generate_html(md_file, refs / "tufte.css", charts_dir if charts_dir.exists() else None)
